on: push
jobs:
  try:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '12.x'
    - run: 'yarn install --frozen-lockfile --non-interactive'
    - uses: ./list
