on: push
jobs:
  try:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v2.3.3
    - uses: actions/setup-node@v1.4.4
      with:
        node-version: '12.x'
    - uses: ./
      with:
        frozen-lockfile: true
    - uses: ./run
      with:
        script: lint
    - uses: ./config/set
      with:
        key: a
        value: b
    - uses: ./config/get
      with:
        input: a
    - uses: ./add
      with:
        silent: true
        no-progress: true
        dev: true
        packages: eslint